
- id: poetry-audit
  name: poetry-audit
  description: run poetry audit to check vulnerabilities of packages in poetry.lock
  entry: poetry audit
  language: python
  language_version: python3
  pass_filenames: false
  files: ^poetry.lock$
  args: ["--with", "dev"]
