ci:
  autoupdate_branch: 'develop'

  # skip hooks from local repo
  skip: [pylint]

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black.git
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort.git
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/docformatter.git
    rev: v1.5.0
    hooks:
      - id: docformatter
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
      - id: mypy
        additional_dependencies: [types-tabulate]
  - repo: local
    # see https://pylint.pycqa.org/en/latest/user_guide/installation/pre-commit-integration.html
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
  - repo: https://github.com/pypa/pip-audit
    rev: v2.4.5
    hooks:
      - id: pip-audit
        stages: [manual]
  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: "0.5.2"
    hooks:
      - id: tox-ini-fmt
