# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black.git
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort.git
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/docformatter.git
    rev: v1.6.0.rc1
    hooks:
      - id: docformatter
        stages: [manual]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1
    hooks:
      - id: mypy
        additional_dependencies: [types-tabulate]
  - repo: local
    # see https://pylint.pycqa.org/en/latest/user_guide/installation/pre-commit-integration.html
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
  - repo: https://github.com/koyeung/ko-poetry-audit-plugin.git
    rev: 0.7.0
    hooks:
      - id: poetry-audit
  - repo: https://github.com/pypa/pip-audit
    rev: v2.4.15
    hooks:
      - id: pip-audit
        stages: [manual]
  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: "0.6.1"
    hooks:
      - id: tox-ini-fmt
