name: Release

on:
  release:
    types: [published]

jobs:

  publish:
    name: Build and publish Python distribution to PYPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
        # no hardcode os-specific path
        id: pip-cache-dir
      - name: pip cache
        id: pip-cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache-dir.outputs.dir }}
          key: pip-${{ github.job }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: pip-${{ github.job }}-

      - run: pip install build

      - name: Show versions
        run: |
          uname -a
          python3 --version
          python3 -m build --version

      - run: python3 -m build

      - name: Publish distribution to PIPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
